const PRODUCTOS_CARGADOS = "PRODUCTOS_CARGADOS";
const NUEVO_PRODUCTO = "NUEVO_PRODUCTO";
const UPDATE_MESSAGES = "UPDATE_MESSAGES";
const NEW_MESSAGE = "NEW_MESSAGE";
const POST_MESSAGE = "POST_MESSAGE";
const LIKE_MESSAGE = "LIKE_MESSAGE";

module.exports = {
    PRODUCTOS_CARGADOS,
    NUEVO_PRODUCTO,
    UPDATE_MESSAGES,
    NEW_MESSAGE,
    POST_MESSAGE,
    LIKE_MESSAGE
}